// frontend/src/app/modules/website/components/navbar/navbar.component.ts
import { Component } from '@angular/core';

interface NavItem {
  label: string;
  path: string;
  exact?: boolean;
  mobileOnly?: boolean;
}

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css'],
})
export class NavbarComponent {
  protected appName = 'Sharing My Games';

  protected navItems: NavItem[] = [
    { label: 'Home', path: '/', exact: true, mobileOnly: true },
    { label: 'Games', path: '/games' },
    { label: 'Tags', path: '/tags' },
  ];
}

<div class="border-b border-base-300 sticky top-0 z-50">
  <div class="navbar container mx-auto py-3">
    <div class="navbar-start md:hidden">
      <div class="dropdown">
        <span role="menu" tabindex="0" class="btn btn-ghost btn-circle">
          <lucide-angular name="menu"></lucide-angular>
        </span>
        <ul role="menu" tabindex="0" class="menu menu-md dropdown-content mt-3 p-2 shadow rounded-box w-52">

          <li role="menuitem" *ngFor="let item of navItems">
            <a [routerLink]="item.path" routerLinkActive="text-primary"
              [routerLinkActiveOptions]="{ exact: item.exact ?? false }">
              {{ item.label }}
            </a>
          </li>
        </ul>
      </div>
    </div>

    <div class='navbar-center md:navbar-start'>
      <a class="btn btn-ghost normal-case text-xl" routerLink="/">
        {{ appName }}
      </a>
      <ng-container *ngFor="let item of navItems" class="hidden sm:block">
        <a *ngIf="!item.mobileOnly" [routerLink]="item.path" class='btn btn-ghost hidden md:inline-flex'
          routerLinkActive="text-primary" [routerLinkActiveOptions]="{ exact: item.exact ?? false }">
          {{ item.label }}
        </a>
      </ng-container>
    </div>

    <div class="navbar-end md:mr-2">
      <app-nav-theme-btn />
    </div>
  </div>
</div>

// frontend/src/components/navbar/navbar.tsx
import {Menu} from 'lucide-react';
import Link from 'next/link';
import {SearchInput} from './search';
import {NsfwToggle} from './nsfwToggle';
import {FeedButton} from './feedButton';
import ActiveLink from '../activeLink';
import {ThemeButton} from './themeButton';

export function NavBar(): JSX.Element {
	return (
		<div className='border-b border-base-300 bg-base-200 sticky top-0 z-50'>
			<div className='navbar container mx-auto py-3'>
				<div className='navbar-start md:hidden'>
					<div className='dropdown'>
						<span role='menu' tabIndex={0} className='btn btn-ghost btn-circle'>
							<Menu />
						</span>
						<ul
							role='menu'
							tabIndex={0}
							className='menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-200 rounded-box w-52'
						>
							<li role='menuitem'>
								<ActiveLink href='/' activeClassName='text-primary'>Home</ActiveLink>
							</li>
							{/* <li role='menuitem'>
								<ActiveLink href='/by-tags' activeClassName='text-primary'>Tags</ActiveLink>
							</li>
							<li role='menuitem'>
								<ActiveLink href='/by-creators' activeClassName='text-primary'>Games</ActiveLink>
							</li> */}
						</ul>
					</div>
				</div>

				<div className='navbar-center md:navbar-start'>
					<Link href='/' className='normal-case text-xl btn btn-ghost'>
                        Sharing my games
					</Link>

					{/* 					<div className='hidden md:flex'>
						<Link href='/by-tags' className='btn btn-ghost'>
                            Tags
						</Link>
						<Link href='/by-creators' className='btn btn-ghost'>
                            Creators
						</Link>
					</div> */}
				</div>

				<div className='navbar-end md:mr-2'>
					<ThemeButton/>
					<FeedButton/>
					<NsfwToggle />
					<SearchInput />
				</div>
			</div>
		</div>
	);
}
