// src/app/modules/website/components/navbar/nav-items/theme-button.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-nav-theme-btn',
  templateUrl: './theme-button.component.html',
})
export class NameComponent {}

<button type="button" class="btn btn-ghost btn-circle"
  [title]="theme ? 'Toggle theme to light mode' : 'Toggle theme to dark mode'" (click)="onButtonClick()">
  <lucide-angular name="sun" *ngIf="theme === 'light'; else isDarkMode" aria-hidden="true"></lucide-angular>
  <ng-template #isDarkMode>
    <lucide-angular name="moon" aria-hidden="true"></lucide-angular>
  </ng-template>
</button>

// frontend/src/components/navbar/themeButton.tsx
'use client';

import {Moon, Sun} from 'lucide-react';
import {useTheme} from 'next-themes';
import {useCallback} from 'react';

export function ThemeButton(): JSX.Element {
	const {theme, setTheme} = useTheme();

	const onClick = useCallback(() => {
		setTheme(theme === 'dark' ? 'light' : 'dark');
	}, [theme, setTheme]);

	return (
		<button
			type='button'
			className='btn btn-ghost btn-circle'
			title={`Toggle theme to ${theme === 'dark' ? 'light' : 'dark'} mode`}
			onClick={onClick}
		>
			{theme === 'light' ? <Sun/> : <Moon/>}
		</button>
	);
}
